# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

client:
  connect_to:
    host: XX.XX.XX.XX
    port: PPPP
  client:
    host: YY.YY.YY.YY
    port: PPPP
server:
  bind:
    host: XX.XX.XX.XX
    port: PPPP
  client:
    host: YY.YY.YY.YY
    port: PPPP
catnip:
  my_ipv4_addr: ZZ.ZZ.ZZ.ZZ
  my_link_addr: "ff:ff:ff:ff:ff:ff"
  my_interface_name: "abcde"
  arp_table:
    "ff:ff:ff:ff:ff:ff": "XX.XX.XX.XX"
    "ff:ff:ff:ff:ff:ff": "YY.YY.YY.YY"
dpdk:
  eal_init: ["", "-c", "0xff", "-n", "4", "-a", "WW:WW.W","--proc-type=auto"]

# vim: set tabstop=2 shiftwidth=2
