# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

#=======================================================================================================================
# Package
#=======================================================================================================================

[package]
name = "demikernel"
version = "1.3.3"
authors = ["Microsoft Corporation"]
edition = "2021"
description = "Kernel-Bypass LibOS Architecture"
readme = "README.md"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/demikernel"
license-file = "LICENSE.txt"

#=======================================================================================================================
# Dependencies
#=======================================================================================================================

[dependencies]

# Third Party
arrayvec = "0.7.4"
async-trait = "0.1.72"
anyhow = "1.0.72"
bit-iter = "1.1.1"
byteorder = "1.4.3"
cfg-if = "1.0.0"
colored = "2.0.0"
crc = "3.0.1"
clap = "4.3.17"
crossbeam-channel = "0.5.8"
ctrlc = "3.2.1"
eui48 = "1.1.0"
flexi_logger = "0.25.5"
futures = "0.3.28"
libc = "0.2.147"
log = "0.4.19"
postcard = { version = "1.0.4", features = ["alloc"] }
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0", features = ["derive", "rc"] }
slab = "0.4.8"
yaml-rust = "0.4.5"
x86 = "0.52.0"

# Demikernel Organization
liburing = { git = "https://github.com/demikernel/liburing-rs", rev = "780827ee3f805d94f9909bd47cd925ee8476a64b", optional = true}
dpdk-rs = { git = "https://github.com/nus-sys/dpdk-rs", rev = "f6dad20be9b23f229ae2536f9c82ecaa3a4a735b", optional = true }

# Windows-specific dependencies.
[target.'cfg(windows)'.dependencies]
# libc implementation in Rust is quite different for Windows and Linux. This library provides the relevant networking
# constants and datastructures for Windows.
windows = { version = "0.44.0", features = ["Win32_Foundation", "Win32_Networking_WinSock"] }
# Provides the Rust socket API for Windows.
socket2 = "0.4.7"

#=======================================================================================================================
# Targets
#=======================================================================================================================

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/rust/lib.rs"

[[test]]
name = "tcp-test"
path = "tests/rust/tcp-test/main.rs"
harness = false

[[test]]
name = "pipe-test"
path = "tests/rust/pipe-test/main.rs"
harness = false

[[test]]
name = "tcp"
path = "tests/rust/tcp.rs"

[[test]]
name = "udp"
path = "tests/rust/udp.rs"

[[test]]
name = "sga"
path = "tests/rust/sga.rs"

[[example]]
name = "udp-dump"
path = "examples/rust/udp-dump.rs"

[[example]]
name = "udp-echo"
path = "examples/rust/udp-echo.rs"

[[example]]
name = "udp-pktgen"
path = "examples/rust/udp-pktgen.rs"

[[example]]
name = "udp-relay"
path = "examples/rust/udp-relay.rs"

[[example]]
name = "pipe-ping-pong"
path = "examples/rust/pipe-ping-pong.rs"

[[example]]
name = "pipe-push-pop"
path = "examples/rust/pipe-push-pop.rs"

[[example]]
name = "udp-push-pop"
path = "examples/rust/udp-push-pop.rs"

[[example]]
name = "udp-ping-pong"
path = "examples/rust/udp-ping-pong.rs"

[[example]]
name = "tcp-dump"
path = "examples/rust/tcp-dump.rs"

[[example]]
name = "tcp-pktgen"
path = "examples/rust/tcp-pktgen.rs"

[[example]]
name = "tcp-push-pop"
path = "examples/rust/tcp-push-pop.rs"

[[example]]
name = "tcp-ping-pong"
path = "examples/rust/tcp-ping-pong.rs"

[[example]]
name = "tcpmig-server-multi"
path = "examples/rust/tcpmig-server-multi.rs"

[[example]]
name = "tcpmig-server-single"
path = "examples/rust/tcpmig-server-single.rs"

[[example]]
name = "tcpmig-client"
path = "examples/rust/tcpmig-client.rs"

[[example]]
name = "dpdk-ctrl"
path = "examples/rust/dpdk-ctrl.rs"

[[example]]
name = "http-server"
path = "examples/rust/http-server.rs"

#=======================================================================================================================
# Features
#=======================================================================================================================

[features]
default = [ "catnap-libos", "catnapw-libos" ]
catnap-libos = [ ]
catnapw-libos = [ ]
catpowder-libos = [ ]
catcollar-libos = [ "liburing" ]
catmem-libos = [ ]
catnip-libos = [ "libdpdk" ]
catloop-libos = [ "catmem-libos" ]
libdpdk = [ "dpdk-rs" ]
mlx4 = [ "dpdk-rs/mlx4" ]
mlx5 = [ "dpdk-rs/mlx5" ]
profiler = [  ]
tcp-migration = [  ]
tcp-migration-profiler = [ "tcp-migration" ]
capybara-log = [  ]

#=======================================================================================================================
# Profile
#=======================================================================================================================

# Build profile used for releases.
[profile.release]
opt-level = 3             # Enable all compiler optimizations.
debug = false             # Do not include any debug info in the binary.
debug-assertions = false  # Do not include any debug assertions in the binary.
overflow-checks = false   # Do not check for overflows at runtime.
lto = "fat"               # Perform link time optimizations across all dependencies (overridden).
panic = "abort"           # Terminate the process upon panic (overridden).
incremental = false       # Disable incremental compilation.
codegen-units = 1         # Produce a single code generation unit (overridden).
rpath = false             # Disable runtime search path.

# Build profile used for development and debugging.
[profile.dev]
opt-level = 0             # Disable all compiler optimizations.
debug = true              # Output full debug info in the binary.
debug-assertions = true   # Include debug assertions in the binary.
overflow-checks = true    # Check for overflows at runtime.
lto = "off"               # Disable link time optimization (overridden).
panic = 'unwind'          # Unwind the stack upon panic.
incremental = true        # Incremental build.
codegen-units = 256       # Produce multiple code generation units.
rpath = false             # Disable runtime search path.
